name: pasartani
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.19
  get: 4.6.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  mockito: ^5.4.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
flutter_native_splash:
  android: true
  ios: true
  image: assets/images/logo.png
  color: "#23AA49"
flutter:
  uses-material-design: true
  assets:
    - .env
